WIP

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,7 +10,11 @@ env:
   TRAEFIK_HTTPS_PORT: 4442
   TRAEFIK_HTTP_PORT: 8042
   HTTPS_PORT_PREFIX: ':4442'
+  REGISTRY_NAMESPACE: ghcr.io/ps-
   DOCKER_TAG: ${{ github.sha }}
+  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
+  REGISTRY_USER: ${{ github.actor }}
+  REGISTRY_PASSWORD: ${{ github.token }}
 
 jobs:
   build_php-fpm-base:
@@ -22,10 +26,13 @@ jobs:
       - name: Build
         run: |
           docker-compose -f docker-compose.init.yml build php-fpm-base
-      - name: Share image
-        uses: ishworkh/docker-image-artifact-upload@v1
+      - name: Push To GHCR
         with:
-          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
+          image: "php-fpm-base"
+          tags: ${{ env.DOCKER_TAG }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.REGISTRY_USER }}
+          password: ${{ env.REGISTRY_PASSWORD }}
 
   build_nginx-fpm-base:
     name: 'Build nginx-fpm-base'
@@ -36,10 +43,13 @@ jobs:
       - name: Build
         run: |
           docker-compose -f docker-compose.init.yml build nginx-fpm-base
-      - name: Share image
-        uses: ishworkh/docker-image-artifact-upload@v1
+      - name: Push To GHCR
         with:
-          image: "nginx-fpm-base:${{ env.DOCKER_TAG }}"
+          image: "nginx-fpm-base"
+          tags: ${{ env.DOCKER_TAG }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.REGISTRY_USER }}
+          password: ${{ env.REGISTRY_PASSWORD }}
 
   build_nodejs-base:
     name: 'Build nodejs-base'
@@ -50,10 +60,13 @@ jobs:
       - name: Build
         run: |
           docker-compose -f docker-compose.init.yml build nodejs-base
-      - name: Share image
-        uses: ishworkh/docker-image-artifact-upload@v1
+      - name: Push To GHCR
         with:
-          image: "nodejs-base:${{ env.DOCKER_TAG }}"
+          image: "nodejs-base"
+          tags: ${{ env.DOCKER_TAG }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.REGISTRY_USER }}
+          password: ${{ env.REGISTRY_PASSWORD }}
 
   build_nginx-cache-purge:
     name: 'Build nginx-cache-purge'
@@ -64,10 +77,13 @@ jobs:
       - name: Build
         run: |
           docker-compose -f docker-compose.init.yml build nginx-cache-purge
-      - name: Share image
-        uses: ishworkh/docker-image-artifact-upload@v1
+      - name: Push To GHCR
         with:
-          image: "nginx-cache-purge:${{ env.DOCKER_TAG }}"
+          image: "nginx-cache-purge"
+          tags: ${{ env.DOCKER_TAG }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.REGISTRY_USER }}
+          password: ${{ env.REGISTRY_PASSWORD }}
 
   build_auth_api:
     name: 'Build Auth API'
@@ -140,211 +156,211 @@ jobs:
           docker-compose -f docker-compose.init.yml build nodejs-base
           docker-compose build databox-client
 
-  build_databox_indexer:
-    name: 'Build Databox Indexer'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Build
-        run: |
-          docker-compose build databox-indexer
-
-  build_databox_indexer_app:
-    name: 'Build Databox Indexer App'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Build
-        run: |
-          docker-compose build databox-indexer-app
-
-  build_expose_api:
-    name: 'Build Expose API'
-    runs-on: ubuntu-latest
-    needs:
-      - build_php-fpm-base
-      - build_nginx-cache-purge
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "nginx-cache-purge:${{ env.DOCKER_TAG }}"
-      - name: Build
-        run: |
-          bin/update-libs.sh
-          docker-compose build expose-api-php expose-api-nginx expose-worker
-
-  build_expose_client:
-    name: 'Build Expose Client'
-    runs-on: ubuntu-latest
-    needs:
-      - build_nodejs-base
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "nodejs-base:${{ env.DOCKER_TAG }}"
-      - name: Build
-        run: |
-          docker-compose -f docker-compose.init.yml build nodejs-base
-          docker-compose build expose-client
-
-  build_matomo:
-    name: 'Build Matomo'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Build
-        run: |
-          docker-compose build matomo-php matomo-nginx
-
-  build_notify_api:
-    name: 'Build Notify API'
-    runs-on: ubuntu-latest
-    needs:
-      - build_php-fpm-base
-      - build_nginx-fpm-base
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "nginx-fpm-base:${{ env.DOCKER_TAG }}"
-      - name: Build
-        run: |
-          bin/update-libs.sh
-          docker-compose build notify-api-php notify-api-nginx notify-worker
-
-  build_report_api:
-    name: 'Build Report API'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Build
-        run: |
-          docker-compose build report-api
-
-  build_uploader_api:
-    name: 'Build Uploader API'
-    runs-on: ubuntu-latest
-    needs:
-      - build_php-fpm-base
-      - build_nginx-fpm-base
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "nginx-fpm-base:${{ env.DOCKER_TAG }}"
-      - name: Build
-        run: |
-          bin/update-libs.sh
-          docker-compose build uploader-api-php uploader-api-nginx uploader-worker
-
-  build_uploader_client:
-    name: 'Build Uploader Client'
-    runs-on: ubuntu-latest
-    needs:
-      - build_nodejs-base
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Download image
-        uses: ishworkh/docker-image-artifact-download@v1
-        with:
-          image: "nodejs-base:${{ env.DOCKER_TAG }}"
-      - name: Build
-        run: |
-          docker-compose -f docker-compose.init.yml build nodejs-base
-          docker-compose build uploader-client
-
-  setup:
-    name: 'Setup stack'
-    runs-on: ubuntu-latest
-    needs:
-      - build_auth_api
-      #- build_dashboard
-      - build_databox_api
-      - build_databox_client
-#      - build_databox_indexer
-#      - build_databox_indexer_app
-      - build_expose_api
-      - build_expose_client
-#      - build_matomo
-      - build_notify_api
-      - build_report_api
-      - build_uploader_api
-      - build_uploader_client
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Setup
-        run: |
-          bin/build.sh
-          docker-compose down --volumes
-          sudo PHRASEA_DOMAIN=${PHRASEA_DOMAIN} bin/dev/append-etc-hosts.sh
-          bin/setup.sh
-      - name: Test
-        run: bin/test.sh
-      - name: Clean containers
-        if: ${{ always() }}
-        run: |
-          docker-compose down --volumes
-      - name: Login to Docker Hub
-        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Push images
-        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
-        run: |
-          bin/build.sh
-          function push() {
-            local n=1
-            local max=5
-            local delay=10
-            while true; do
-              docker-compose \
-                -f docker-compose.yml \
-                -f docker-compose.prod.yml \
-                -f docker-compose.report-elk.yml && break || {
-                if [[ $n -lt $max ]]; then
-                  ((n++))
-                  echo "Push failed. Attempt $n/$max:"
-                  sleep $delay;
-                else
-                  echo "Push has failed after $n attempts." >&2
-                  exit 1
-                fi
-              }
-            done
-          }
-          if [[ -z "${DOCKERHUB_USERNAME}" ]]; then
-            push
-          else
-            echo "Publish step skipped."
-          fi
+#  build_databox_indexer:
+#    name: 'Build Databox Indexer'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Build
+#        run: |
+#          docker-compose build databox-indexer
+#
+#  build_databox_indexer_app:
+#    name: 'Build Databox Indexer App'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Build
+#        run: |
+#          docker-compose build databox-indexer-app
+#
+#  build_expose_api:
+#    name: 'Build Expose API'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_php-fpm-base
+#      - build_nginx-cache-purge
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "nginx-cache-purge:${{ env.DOCKER_TAG }}"
+#      - name: Build
+#        run: |
+#          bin/update-libs.sh
+#          docker-compose build expose-api-php expose-api-nginx expose-worker
+#
+#  build_expose_client:
+#    name: 'Build Expose Client'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_nodejs-base
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "nodejs-base:${{ env.DOCKER_TAG }}"
+#      - name: Build
+#        run: |
+#          docker-compose -f docker-compose.init.yml build nodejs-base
+#          docker-compose build expose-client
+#
+#  build_matomo:
+#    name: 'Build Matomo'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Build
+#        run: |
+#          docker-compose build matomo-php matomo-nginx
+#
+#  build_notify_api:
+#    name: 'Build Notify API'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_php-fpm-base
+#      - build_nginx-fpm-base
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "nginx-fpm-base:${{ env.DOCKER_TAG }}"
+#      - name: Build
+#        run: |
+#          bin/update-libs.sh
+#          docker-compose build notify-api-php notify-api-nginx notify-worker
+#
+#  build_report_api:
+#    name: 'Build Report API'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Build
+#        run: |
+#          docker-compose build report-api
+#
+#  build_uploader_api:
+#    name: 'Build Uploader API'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_php-fpm-base
+#      - build_nginx-fpm-base
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "php-fpm-base:${{ env.DOCKER_TAG }}"
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "nginx-fpm-base:${{ env.DOCKER_TAG }}"
+#      - name: Build
+#        run: |
+#          bin/update-libs.sh
+#          docker-compose build uploader-api-php uploader-api-nginx uploader-worker
+#
+#  build_uploader_client:
+#    name: 'Build Uploader Client'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_nodejs-base
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Download image
+#        uses: ishworkh/docker-image-artifact-download@v1
+#        with:
+#          image: "nodejs-base:${{ env.DOCKER_TAG }}"
+#      - name: Build
+#        run: |
+#          docker-compose -f docker-compose.init.yml build nodejs-base
+#          docker-compose build uploader-client
+#
+#  setup:
+#    name: 'Setup stack'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build_auth_api
+#      #- build_dashboard
+#      - build_databox_api
+#      - build_databox_client
+##      - build_databox_indexer
+##      - build_databox_indexer_app
+#      - build_expose_api
+#      - build_expose_client
+##      - build_matomo
+#      - build_notify_api
+#      - build_report_api
+#      - build_uploader_api
+#      - build_uploader_client
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#      - name: Setup
+#        run: |
+#          bin/build.sh
+#          docker-compose down --volumes
+#          sudo PHRASEA_DOMAIN=${PHRASEA_DOMAIN} bin/dev/append-etc-hosts.sh
+#          bin/setup.sh
+#      - name: Test
+#        run: bin/test.sh
+#      - name: Clean containers
+#        if: ${{ always() }}
+#        run: |
+#          docker-compose down --volumes
+#      - name: Login to Docker Hub
+#        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
+#        uses: docker/login-action@v1
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#      - name: Push images
+#        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
+#        run: |
+#          bin/build.sh
+#          function push() {
+#            local n=1
+#            local max=5
+#            local delay=10
+#            while true; do
+#              docker-compose \
+#                -f docker-compose.yml \
+#                -f docker-compose.prod.yml \
+#                -f docker-compose.report-elk.yml && break || {
+#                if [[ $n -lt $max ]]; then
+#                  ((n++))
+#                  echo "Push failed. Attempt $n/$max:"
+#                  sleep $delay;
+#                else
+#                  echo "Push has failed after $n attempts." >&2
+#                  exit 1
+#                fi
+#              }
+#            done
+#          }
+#          if [[ -z "${DOCKERHUB_USERNAME}" ]]; then
+#            push
+#          else
+#            echo "Publish step skipped."
+#          fi
